const categories = [
  {
    name: 'Snacks',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/541/541836.png',
  },
  {
    name: 'Drinks',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3126/3126588.png',
  },
  {
    name: 'Vegetables',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/2329/2329903.png',
  },
  {
    name: 'Fruits',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3081/3081887.png',
  },
  {
    name: 'Personal Care',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/1986/1986195.png',
  },
  {
    name: 'household supplies',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/2868/2868986.png',
  },
  {
    name: 'Cheese and dairy',
    imageUrl: 'https://cdn-icons.flaticon.com/png/512/1892/premium/1892619.png?token=exp=1652990532~hmac=54c77e64a1b4b8193ca5871a1559711b',
  },
  {
    name: 'Baking',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/2917/2917630.png',
  },
];

const products = [
  {
    name: 'Lays chips',
    imageUrl: 'https://m.media-amazon.com/images/I/71J93R3+TkL._SX522_.jpg',
    price: 2.5,
    details: '',
    categoryId: 1,
  },
  {
    name: 'Nutella',
    imageUrl: 'https://pbs.twimg.com/profile_images/563000683037597696/AqYerA4D_400x400.png',
    price: 10,
    details: 'One 26.5 oz jar of delicious Nutella hazelnut spread, the perfect topping for pancakes, waffles, toast, and more!,The Original Hazelnut Spread…unique in all the world.Made from quality ingredients like roasted hazelnuts and cocoa.',
    categoryId: 1,
  },
  {
    name: 'Twix',
    imageUrl: 'https://www.fivestartrading-holland.eu/images/product_images/popup_images/twix-single-25x50gr.jpg',
    price: 2,
    details: 'Twix is a caramel shortbread chocolate bar made by Mars, consisting of a biscuit applied with other confectionery toppings and coatings (most frequently caramel and milk chocolate).Twix are packaged with one, two or four bars in a wrapper.',
    categoryId: 1,
  },
  {
    name: 'Candy',
    imageUrl: 'https://www.confitelia.com/4367-big_default/yummi-time-gummies-haribo.jpg',
    price: 5,
    details: ' fruit gums in the shape of stylised bears, that are two centimetres in size and consist of sugar, sugar syrup, colourants and flavourings',
    categoryId: 1,
  },
  {
    name: 'marshmallow',
    imageUrl: 'https://m.media-amazon.com/images/I/819PBB01j9L._SX522_.jpg',
    price: 20,
    details: 'A marshmallow is a sweet, soft treat. Marshmallows are sometimes melted and turned into a sugary topping for ice cream or a filling for baked goods. Marshmallows are made of gelatin and sugar, with a dusty powdered sugar surface.',
    categoryId: 1,
  },
  {
    name: 'Cashew Mix',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-2-1.jpg',
    price: 10,
    details: '',
    categoryId: 1,
  },
  {
    name: 'Galaxy',
    imageUrl: 'https://cdnprod.mafretailproxy.com/sys-master-root/h8c/hed/13698686287902/527328_main.jpg_480Wx480H',
    price: 3.5,
    details: 'A famous chocolate made of wafers covered with chocolate',
    categoryId: 1,
  },
  {
    name: 'Molto',
    imageUrl: 'https://cdnprod.mafretailproxy.com/sys-master-root/hfc/h53/12820741652510/528055_main.jpg_1700Wx1700H',
    price: 1,
    details: 'Molto sandwich with chocolate and hazelnut paste, suitable for breakfast',
    categoryId: 1,
  },
  {
    name: 'Cola',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 2.5,
    details: 'Perfect for parties, meals, and celebrations big and small Great for portion control - each can has only 100 calories The official soft drink of the National Football League, Major League Baseball, and cola lovers everywhere',
    categoryId: 2,
  },
  {
    name: 'Iced Coffee',
    imageUrl: 'https://halgoom.com/wp-content/uploads/2020/06/Luna-Iced-Coffe-Moca-190ml.jpg',
    price: 3.5,
    details: 'Ice Coffee Luna is one of the best and most delicious cold coffee, available in several Arab and European countries. Weight: 190 grams',
    categoryId: 2,
  },
  {
    name: 'Waters',
    imageUrl: 'https://cdn.miswag.me/images/images/miswag_0raP0wAUwrXc.jpg',
    price: 4,
    details: 'Water Nestle helps maintain energy metabolism for an active lifestyle',
    categoryId: 2,
  },
  {
    name: 'Birell',
    imageUrl: 'https://aqrab-market.com/wp-content/uploads/2022/04/Nq9gi9cDk1phTKYuCWV15ZDkEAVGgFChzlJlJhmX.jpeg',
    price: 3,
    details: 'Birell is a pure alcohol-free barley drink. It is one of the famous drinks in many countries of the world. It is known for its high nutritional value, as it contains a high percentage of essential elements for the body such as fiber and antioxidants, in addition to vitamins, minerals, carbohydrates and sugars.',
    categoryId: 2,
  },
  {
    name: 'Schweppes',
    imageUrl: 'https://aqrab-market.com/wp-content/uploads/2022/04/090e2d02-0977-49ae-81ce-418392a9dc7e.__CR00300300_PT0_SX300_V1___.jpg',
    price: 4,
    details: 'Mix barley and pineapple taste with the expertise of Schweppes, Pineapple Flavored Barley Drink Ingredients: Carbonated water, sugar or fructose syrup, acidity regulators (citric acid - malic acid), malt extract, flavors, preservatives within permissible limits (potassium sorbate and sodium benzoate), foaming agent (quillalia extract) .',
    categoryId: 2,
  },
  {
    name: 'Reishi coffee',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-12-1.jpg',
    price: 16,
    details: 'Mood-modifying coffee, increasing body activity, alerting the mind and feeling alert',
    categoryId: 2,
  },
  {
    name: 'Ahmed Tea',
    imageUrl: 'https://www.maisonsyrienne.lu/1590-large_default/%D8%B4%D8%A7%D9%8A-%D8%A3%D8%AD%D9%85%D8%AF-%D8%B4%D8%A7%D9%8A-%D8%A7%D9%84%D9%87%D9%8A%D9%84-500-%D8%AC%D8%B1%D8%A7%D9%85.jpg',
    price: 18,
    details: 'English tea, made from the finest Ceylon and Kenyan teas, and is exported to more than 70 countries around the world',
    categoryId: 2,
  },
  {
    name: 'Mango',
    imageUrl: 'https://images.heb.com/is/image/HEBGrocery/001204699?fit=constrain,1&wid=800&hei=800&fmt=jpg&qlt=85,0&resMode=sharp2&op_usm=1.75,0.3,2,0',
    price: 8,
    details: 'Natural mango juice helps lower blood pressure, which relieves pressure on the circulatory system in general, and reduces the chances of heart disease and strokes.',
    categoryId: 2,
  },
  {
    name: 'Carrot',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/thumbnail-1.jpg',
    price: 2,
    details: 'Carrots’ water content ranges from 86–95%, and the edible portion consists of around 10% carbs .Carrots contain very little fat and protein',
    categoryId: 3,
  },
  {
    name: 'lemon',
    imageUrl: 'https://primefoods-eg.com/site/wp-content/uploads/2020/10/shutterstock_92433031.jpg',
    price: 2,
    details: 'Lemons give flavor to baked goods, sauces, salad dressings, marinades, drinks, and desserts, and they are also a good source of vitamin C.One lemon can provide of vitamin C.',
    categoryId: 3,
  },
  {
    name: 'paprika',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/thumbnail-2.jpg',
    price: 7.5,
    details: 'Paprika contains capsaicin. also, it has antioxidant properties, can help reduce the risk of cancer and heart disease, improve immunity, and even alleviate gas.',
    categoryId: 3,
  },
  {
    name: 'Lettuce',
    imageUrl: 'https://cdnprod.mafretailproxy.com/sys-master-root/h53/hb7/13374542184478/449348_main.jpg_480Wx480H',
    price: 8,
    details: 'Lettuce is a leafy vegetable, famous for giving salads their base,Lettuce is a source of vitamin K, which helps strengthen bones. Consuming adequate amounts of vitamin K can also reduce your risk of bone fracture',
    categoryId: 3,
  },
  {
    name: 'Cucumber',
    imageUrl: 'https://alishmart.se/wp-content/uploads/2020/12/Cucumber-lebanese-39.90.jpg',
    price: 2.5,
    details: 'Cucumbers have a mild, refreshing taste and a high water content. They can help relieve dehydration and are pleasant to eat in hot weather.',
    categoryId: 3,
  },
  {
    name: 'Tomato',
    imageUrl: 'https://kiranacompare.com/wp-content/uploads/2020/11/71DYmqoq-VL._SL1024_.jpg',
    price: 1.5,
    details: 'Tomatoes are the major dietary source of the antioxidant lycopene, which has been linked to many health benefits, including reduced risk of heart disease and cancer.',
    categoryId: 3,
  },
  {
    name: 'Eggplant',
    imageUrl: 'https://www.highmowingseeds.com/media/catalog/product/cache/6cbdb003cf4aae33b9be8e6a6cf3d7ad/2/4/2471-1.jpg',
    price: 3,
    details: 'Eggplants are a nutrient-dense food, meaning they contain a good amount of vitamins, minerals and fiber in few calories.',
    categoryId: 3,
  },
  {
    name: 'onion',
    imageUrl: 'https://produits.bienmanger.com/38436-0w600h600_Organic_Grano_Oro_Onion.jpg',
    price: 1.5,
    details: 'Onions are a nutrient-dense food, meaning that they are high in vitamins, minerals, and antioxidants while being low in calories.',
    categoryId: 3,
  },
  {
    name: 'corn',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/thumbnail-9.jpg',
    price: 11,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 3,
  },
  {
    name: 'Avocado',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/thumbnail-11.jpg',
    price: 4.5,
    details: '',
    categoryId: 3,
  },
  {
    name: 'Strawberry',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/cat-2.png',
    price: 8,
    details: 'Strawberries are also called the fruit of grace or berries, and they are rich in mineral salts, as they contain calcium, iron and phosphorous, and they also contain citric acid, apple acid, fructose, and high amounts of vitamins A, B, and C.',
    categoryId: 4,
  },
  {
    name: 'Graviola',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/cat-5.png',
    price: 20,
    details: 'The fruit of the cream contains vitamin A, the fruit of the cream may contribute to a significant improvement in the health of your eyes and vision. Vitamin C, known for its antioxidant properties, also reduces the chances of developing various eye diseases. The fruit of the cream helps reduce the risk of eye problems that arise naturally with age.',
    categoryId: 4,
  },
  {
    name: 'Grape',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/cat-6.png',
    price: 25,
    details: 'Grapes are one of the fruits with good nutritional and therapeutic value. It has been known since ancient times and contains many vitamins',
    categoryId: 4,
  },
  {
    name: 'Orange',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/cat-7.png',
    price: 16,
    details: 'The orange is a type of citrus produced by the orange tree. It is an excellent source of vitamin C. The vitamin C in oranges helps in the absorption of calcium in the body. It also contains vitamin A and is a source of sodium, potassium, magnesium, copper, sulfur and chlorine.',
    categoryId: 4,
  },
  {
    name: 'Apple',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/cat-9.png',
    price: 8,
    details: 'Instamrt apples have a firm texture and a super sweet flavour, and can be eaten daily as a snack, ideal for use in pies, and good for storing',
    categoryId: 4,
  },
  {
    name: 'Persimmon',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/cat-11.png',
    price: 10,
    details: 'Persimmons contain many nutrients that belong to the family of B-complex vitamins, and they also contain large amounts of folic acid and thiamine, which are very important in the various metabolic processes in the body.',
    categoryId: 4,
  },
  {
    name: 'Kiwi',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/cat-12.png',
    price: 10,
    details: 'It is an oval shaped fruit. The rind of the fruit is brown, while the pulp is often green and contains small, edible black seeds',
    categoryId: 4,
  },
  {
    name: 'Banana',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/thumbnail-4.jpg',
    price: 4,
    details: 'Bananas contain soluble fiber, especially pectin, and a high percentage of water, as 75% of their mass is water.',
    categoryId: 4,
  },
  {
    name: 'watermelon',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/thumbnail-5.jpg',
    price: 5,
    details: 'Watermelon is one of the most popular summer fruits, which helps to counteract the heat and replace lost fluids from the body',
    categoryId: 4,
  },
  {
    name: 'Mango',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/thumbnail-7.jpg',
    price: 15,
    details: 'Mango is one of the tropical fruits rich in dietary fiber, which made it famous since ancient times for calming the stomach, treating digestive problems and constipation.',
    categoryId: 4,
  },
  {
    name: 'Pomegranate',
    imageUrl: 'https://wp.alithemes.com/html/nest/demo/assets/imgs/shop/thumbnail-10.jpg',
    price: 23,
    details: 'Pomegranate is a good source of vitamin C, as 100 grams of pomegranate provides about 17% of our daily need for vitamin C, which is very important for strengthening immunity, and pomegranate contains many other vitamins such as: Vitamin K',
    categoryId: 4,
  },
  {
    name: 'Toilet Paper',
    imageUrl: 'https://images.heb.com/is/image/HEBGrocery/000912650',
    price: 20,
    details: 'Quilted Northern Ultra Soft & Strong toilet paper is soft, strong & made sustainably for a comfy, reliable clean',
    categoryId: 6,
  },
  {
    name: 'Tide with Downy Liquid Soap',
    imageUrl: 'https://i5.walmartimages.com/asr/6cd4049e-cccb-4214-9da2-d20a4eb57f98.c32becd6581d4257c23078c3ebb901c5.jpeg',
    price: 35,
    details: 'Tide + Downy liquid detergent offers Tide’s powerful cleaning and freshness plus the color protection of Downy ,Loaded with softening ingredients that add a smooth layer of comfort to the fibers in your fabrics.',
    categoryId: 6,
  },
  {
    name: 'Trash Bags',
    imageUrl: 'https://m.media-amazon.com/images/I/81UB6Mk4DOL._AC_SX425_.jpg',
    price: 15,
    details: 'TOUGHNESS YOU CAN TRUST—Tackle everyday kitchen waste, post-party debris or your next big cleanup project with these strong, versatile drawstring trash bags.',
    categoryId: 6,
  },
  {
    name: 'Stainless Steel Scrubbers',
    imageUrl: 'https://m.media-amazon.com/images/I/91Geq9zGy-L._AC_SX425_.jpg',
    price: 8,
    details: 'Cuts through and removes tough soil & burnt-on food FAST!,Ideal for broiler pans. Long-lasting and Durable,Non-Rust.',
    categoryId: 6,
  },
  {
    name: 'Fabuloso All Purpose Cleaner',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0592/8832/2220/products/81TxupMrK4L._SL1500.jpg?v=1629903254',
    price: 13,
    details: 'Fabuloso All Purpose Cleaner, Lavender, Bathroom Cleaner, Toilet Cleaner, Floor Cleaner, Shower and Glass Cleaner, Mop Cleanser, Kitchen Pots and Pans Degreaser',
    categoryId: 6,
  },
  {
    name: 'Dawn Dish Soap',
    imageUrl: 'https://res.cloudinary.com/pgone/image/upload/pgone/dawn-dish/en-us/prod/images/okn47frwsxibbilostkq',
    price: 11,
    details: 'Dawn Ultra Antibacterial Dish Soap Contains 2x Grease Cleaning Power (cleaning ingredients per drop vs.Dawn Non-Concentrated .',
    categoryId: 6,
  },
  {
    name: 'Harpic Powerplus Original',
    imageUrl: 'https://viharbazar.com/wp-content/uploads/2021/09/HARPIC.jpg',
    price: 15,
    details: ' This cleaner powers through tough stains and toilet bowl rings in seconds to leave your toilet bowl sparkling clean. The angled bottle makes it easy to reach tough stains in tricky areas.',
    categoryId: 6,
  },
  {
    name: 'Downy',
    imageUrl: 'https://i5.walmartimages.com/asr/f17cc270-ea65-4128-8ad7-1d14a677f2dc.31f0e4d82aaf76ae4f7a1f8ba28e2dc6.jpeg',
    price: 30,
    details: 'Conditions to help prevent stretching, fading, and fuzz.Leaves long-lasting freshness and softens fabrics.Reduces more wrinkles than detergent alone',
    categoryId: 6,
  },
  {
    name: 'Dove',
    imageUrl: 'https://m.media-amazon.com/images/I/810Q4TA3KmL._SX425_.jpg',
    price: 60,
    details: 'Dove Men+Care Body Wash for Mens Skin Care Extra Fresh Effectively Washes Away Bacteria While Nourishing Your Skin 18 oz 4 Count',
    categoryId: 5,
  },
  {
    name: 'Dove',
    imageUrl: 'https://m.media-amazon.com/images/I/51or9--aOvL._SX425_.jpg',
    price: 55,
    details: 'Dove Deep Moisture Body Wash For Dry Skin Moisturizing Body Wash Transforms Even The Driest Skin In One Shower 22 oz 4 Count',
    categoryId: 5,
  },
  {
    name: 'Shower Loofah',
    imageUrl: 'https://m.media-amazon.com/images/I/81k9OCupQ3S._AC_SX569_.jpg',
    price: 28,
    details: 'MainBasics Bath Shower Loofah Sponge Pouf Body Scrubber Exfoliator (Set of 3)',
    categoryId: 5,
  },
  {
    name: 'teeth cleaner',
    imageUrl: 'https://m.media-amazon.com/images/I/71nQQ6vkpNL._SX425_.jpg',
    price: 43,
    details: 'Crest Charcoal 3D White Toothpaste, Whitening Therapy Deep Clean with Fluoride, Invigorating Mint, 4.1 Ounce, Pack of 3',
    categoryId: 5,
  },
  {
    name: 'teeth cleaner',
    imageUrl: 'https://m.media-amazon.com/images/I/81yFnyNEHrL._SX425_.jpg',
    price: 79,
    details: 'Sensodyne Repair and Protect Whitening Toothpaste, Toothpaste for Sensitive Teeth and Cavity Prevention, 3.4 oz (Pack of 4)',
    categoryId: 5,
  },
  {
    name: 'teeth cleaner',
    imageUrl: 'https://m.media-amazon.com/images/I/91j4JnGmjDL._SX425_.jpg',
    price: 31.5,
    details: 'Colgate Whitening Toothpaste for Sensitive Teeth, Enamel Repair and Cavity Protection, Fresh Mint Gel, 6 Oz, Pack of 3',
    categoryId: 5,
  },
  {
    name: 'Soap',
    imageUrl: 'https://m.media-amazon.com/images/I/61If06P-EbS._SX425_.jpg',
    price: 94,
    details: 'Dr. Squatch All Natural Bar Soap for Men, 3 Bar Variety Pack, Pine Tar, Cedar Citrus and Gold Moss',
    categoryId: 5,
  },
  {
    name: 'Shampoo',
    imageUrl: 'https://m.media-amazon.com/images/I/71Ayuiq1PmL._SX425_.jpg',
    price: 59,
    details: 'Pantene Shampoo Twin Pack with Hair Treament, Daily Moisture Renewal for Dry Hair, Safe for Color-Treated Hair',
    categoryId: 5,
  },
  {
    name: 'Chtoora Halloumi Light',
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0609/9071/8194/products/chtoora-01-scaled_1024x1024.jpg?v=1635948113',
    price: 12,
    details:
      'Chtoora Halloumi Light is a semi-hard, unripped cheese made from a mixture of goat\'s and sheep\'s milk. You can fry or grill it, and enjoy it the way you want',
    categoryId: 7,
  },
  {
    name: 'Puck Cream Cheese',
    imageUrl:
      'https://www.luluhypermarket.com/medias/115286-01.jpg-1200Wx1200H?context=bWFzdGVyfGltYWdlc3w1MjU4NTR8aW1hZ2UvanBlZ3xoOTcvaDI4LzExODY1MzI2ODc4NzUwLzExNTI4Ni0wMS5qcGdfMTIwMFd4MTIwMEh8MzUzM2VkNzM1YTcwNTgyOTVjYmQyNTE4ZWQyNjI5ZmRiYzU2M2M0MDRiZjc0OTAzMzRhZmZlZGVmNTc4YTM4Zg',
    price: 20,
    details:
      'Savour taste buds like never before with this cheese. It has a tangy flavour that is sure to tantalize your taste buds. It ranks high in calcium to provide your bones with nourishment and care',
    categoryId: 7,
  },
  {
    name: 'Full Fat Fresh Milk',
    imageUrl:
      'https://www.almarai.com/wp-content/uploads/2018/10/20920-MILK-FF-1GALLON-HDPE-NFPC-EN_WEB.jpg',
    price: 10,
    details:
      'Packed with important nutrients like Calcium, Phosphorus, B Vitamins, Potassium and Vitamin D. Excellent source of protein,It May prevent osteoporosis and bone fractures and even help you maintain a healthy weight',
    categoryId: 7,
  },
  {
    name: 'Almarai Strawberry Flavoured',
    imageUrl:
      'https://cdnprod.mafretailproxy.com/sys-master-root/h73/hc6/16001329299486/993305_main.jpg_480Wx480H',
    price: 1.5,
    details:
      'Known to be a perfect cold dessert, Almarai Strawberry Yoghurt can be a tremendous post dinner frozen delight. It is semi solid and easy to digest. The chilled food item can help soothe the piping hot main course you had earlier',
    categoryId: 7,
  },
  {
    name: 'GoGo squeeZ yogurtZ Pack',
    imageUrl:
      'https://m.media-amazon.com/images/I/51JkWdqjURL.jpg',
    price: 20,
    details:
      'SMOOTH & CREAMY YOGURT SNACK POUCHES: GoGo squeeZ yogurtZ are made from real yogurt and blueberries and strawberries for a smooth, creamy and tasty yogurt snack kids will love—no spoon, no mess!',
    categoryId: 7,
  },
  {
    name: 'Mozzarella',
    imageUrl:
      'https://www.galbani.com/images/product/mozzarella.png',
    price: 16,
    details:
      'Mozzarella is a plastic or stretched-curd cheese; the curd is mixed with heated whey and stretched and kneaded until it attains a smooth, pliable consistency.',
    categoryId: 7,
  },
  {
    name: 'SHEEP MILK CHEESE',
    imageUrl:
      'https://presidentcheese-y0leynmj.netdna-ssl.com/wp-content/uploads/2021/08/President_SheepsMilk_MarinatedCubes_35oz_OliveOil_500x500.png',
    price: 5,
    details:
      'Delicious Sheep Milk French Cheese Cubes are pre-diced and marinated in the perfect amount of olive oil with natural flavor added.',
    categoryId: 7,
  },
  {
    name: 'Kiri',
    imageUrl:
      'https://elaskitchenbd.com/wp-content/uploads/2022/03/8219-01.jpg',
    price: 15,
    details:
      'Pack of 6 portions, 108 ounces pack. Creamy processed cheese. Product of France',
    categoryId: 7,
  },
  {
    name: 'Bread Sticks',
    imageUrl: 'https://care4mall.online/wp-content/uploads/2022/05/fefgesf-1.png',
    price: 5,
    details: 'Sham cakes with thyme, Weight: 400gm',
    categoryId: 8,
  },
  {
    name: 'Bread Sticks',
    imageUrl: 'https://care4mall.online/wp-content/uploads/2022/05/fewgeg.png',
    price: 5,
    details: 'Sham bran cakes, Weight: 400gm',
    categoryId: 8,
  },
  {
    name: 'Baked Bread',
    imageUrl: 'https://www.ubuy.hu/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvOTFXWHJ2RGl0SUwuX1NMMTUwMF8uanBn.jpg',
    price: 5,
    details: '',
    categoryId: 8,
  },
  {
    name: 'mini cup cake pakage',
    imageUrl: 'https://cdn11.bigcommerce.com/s-l5dryyv/images/stencil/1280x1280/products/10272/6582/BXX00096-main1__28674.1596744857.jpg?c=2',
    price: 4,
    details: '',
    categoryId: 8,
  },
];

const users = [{
  id: 10,
  name: 'insta',
  email: 'yosra@gmail.com',
  mobile: '4525245',
  address: 'sgsggdgsg',
  password: '$2b$10$5Or.3zVU/tuQnKIVZXjjyObIgJvuhk/xHS41EaMBWXgK1LPQjpk0O',
  isAdmin: true,
}];

const productsOrders = [
  { quantity: 50, productId: 1 },
  { quantity: 50, productId: 2 },
  { quantity: 50, productId: 3 },
  { quantity: 50, productId: 4 },
  { quantity: 50, productId: 5 },
  { quantity: 50, productId: 6 },
  { quantity: 50, productId: 7 },
  { quantity: 50, productId: 8 },
  { quantity: 50, productId: 9 },
  { quantity: 50, productId: 10 },
  { quantity: 50, productId: 11 },
  { quantity: 50, productId: 12 },
  { quantity: 50, productId: 13 },
  { quantity: 50, productId: 14 },
  { quantity: 50, productId: 15 },
  { quantity: 50, productId: 16 },
  { quantity: 50, productId: 17 },
  { quantity: 50, productId: 18 },
  { quantity: 50, productId: 19 },
  { quantity: 50, productId: 20 },
  { quantity: 50, productId: 21 },
  { quantity: 50, productId: 22 },
  { quantity: 50, productId: 23 },
  { quantity: 50, productId: 24 },
  { quantity: 50, productId: 25 },
  { quantity: 50, productId: 26 },
  { quantity: 50, productId: 27 },
  { quantity: 50, productId: 28 },
  { quantity: 50, productId: 29 },
  { quantity: 50, productId: 30 },
  { quantity: 50, productId: 31 },
  { quantity: 50, productId: 32 },
  { quantity: 50, productId: 33 },
  { quantity: 50, productId: 34 },
  { quantity: 50, productId: 35 },
  { quantity: 50, productId: 36 },
  { quantity: 50, productId: 37 },
  { quantity: 50, productId: 38 },
  { quantity: 50, productId: 39 },
  { quantity: 50, productId: 40 },
  { quantity: 50, productId: 41 },
  { quantity: 50, productId: 42 },
  { quantity: 50, productId: 43 },
  { quantity: 50, productId: 44 },
  { quantity: 50, productId: 45 },
  { quantity: 50, productId: 46 },
  { quantity: 50, productId: 47 },
  { quantity: 50, productId: 48 },
  { quantity: 50, productId: 49 },
  { quantity: 50, productId: 50 },
  { quantity: 50, productId: 51 },
  { quantity: 50, productId: 52 },
  { quantity: 50, productId: 53 },
  { quantity: 50, productId: 54 },
  { quantity: 50, productId: 55 },
  { quantity: 50, productId: 56 },
  { quantity: 50, productId: 57 },
  { quantity: 50, productId: 58 },
  { quantity: 50, productId: 59 },
  { quantity: 50, productId: 60 },
  { quantity: 50, productId: 61 },
  { quantity: 50, productId: 62 },
  { quantity: 50, productId: 63 },
  { quantity: 50, productId: 64 },
  { quantity: 50, productId: 65 },
  { quantity: 10, productId: 1 },
  { quantity: 5, productId: 1 },
  { quantity: 1, productId: 1, orderId: 1 },
  { quantity: 5, productId: 2, orderId: 1 },

];

const order = [{
  date: new Date(),
  totalPrice: 100,
  paidPrice: 200,
  status: 'pending',
  supplier: 'admin',
  isSupplied: false,
  mobile: '0599832',
  address: 'string',
},
{
  date: new Date(),
  totalPrice: 200,
  paidPrice: 200,
  status: 'pending',
  supplier: 'admin',
  isSupplied: false,
  mobile: '0599832',
  address: 'string',
},
{
  date: new Date(),
  totalPrice: 300,
  paidPrice: 200,
  status: 'approved',
  supplier: 'admin',
  isSupplied: false,
  mobile: '0599832',
  address: 'string',
}];

export {
  products, categories, users, productsOrders, order,
};
