const categories = [
  {
    name: 'Food',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/541/541836.png',
  },
  {
    name: 'Drinks',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3126/3126588.png',
  },
  {
    name: 'Vegetables',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/2329/2329903.png',
  },
  {
    name: 'Fruits',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/3081/3081887.png',
  },
];

const products = [
  {
    name: 'Cola',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Cola1',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Cola2',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Cola3',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Cola4',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Cola6',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Cola6',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Rice',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-1.jpg',
    price: 10,
    details: '',
    categoryId: 1,
  },
  {
    name: 'Tomato',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-6.jpg',
    price: 30,
    details: '',
    categoryId: 3,
  },
  {
    name: 'Banana',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-4.jpg',
    price: 40,
    details: '',
    categoryId: 4,
  },
  {
    name: 'Cola',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Rice',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-1.jpg',
    price: 10,
    details: '',
    categoryId: 1,
  },
  {
    name: 'Tomato',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-6.jpg',
    price: 30,
    details: '',
    categoryId: 3,
  },
  {
    name: 'Banana',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-4.jpg',
    price: 40,
    details: '',
    categoryId: 4,
  },
  {
    name: 'Cola',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Rice',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-1.jpg',
    price: 10,
    details: '',
    categoryId: 1,
  },
  {
    name: 'Tomato',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-6.jpg',
    price: 30,
    details: '',
    categoryId: 3,
  },
  {
    name: 'Banana',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-4.jpg',
    price: 40,
    details: '',
    categoryId: 4,
  },
  {
    name: 'Cola',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Rice',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-1.jpg',
    price: 10,
    details: '',
    categoryId: 1,
  },
  {
    name: 'Tomato',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-6.jpg',
    price: 30,
    details: '',
    categoryId: 3,
  },
  {
    name: 'Banana',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-4.jpg',
    price: 40,
    details: '',
    categoryId: 4,
  },
  {
    name: 'Cola',
    imageUrl: 'https://diplomats.layam.com/media/catalog/product/cache/b7dfd230b7d734c0966cd84b3ae2fb1b/3/7/3720208_1.jpg',
    price: 20,
    details: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    categoryId: 2,
  },
  {
    name: 'Rice',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-1.jpg',
    price: 10,
    details: '',
    categoryId: 1,
  },
  {
    name: 'Tomato',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-6.jpg',
    price: 30,
    details: '',
    categoryId: 3,
  },
  {
    name: 'Banana',
    imageUrl: 'http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-16-4.jpg',
    price: 40,
    details: '',
    categoryId: 4,
  },
];

const users = [{
  id: 10,
  name: 'insta',
  email: 'yosra@gmail.com',
  mobile: 4525245,
  address: 'sgsggdgsg',
  password: '$2b$10$5Or.3zVU/tuQnKIVZXjjyObIgJvuhk/xHS41EaMBWXgK1LPQjpk0O',
  isAdmin: true,
}];
export { products, categories, users };
